/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#4648d4',
        'primary-container': '#6063ee',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-primary-fixed': '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'inverse-primary': '#c0c1ff',
        'secondary': '#5d5d67',
        'secondary-container': '#e3e1ed',
        'secondary-fixed': '#e3e1ed',
        'secondary-fixed-dim': '#c7c5d1',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#64636d',
        'on-secondary-fixed': '#1a1b23',
        'on-secondary-fixed-variant': '#46464f',
        'tertiary': '#5148d7',
        'tertiary-container': '#6a63f2',
        'tertiary-fixed': '#e3dfff',
        'tertiary-fixed-dim': '#c3c0ff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#020026',
        'on-tertiary-fixed': '#100069',
        'on-tertiary-fixed-variant': '#372abf',
        'surface': '#fcf8ff',
        'surface-dim': '#dad6ff',
        'surface-bright': '#fcf8ff',
        'surface-container': '#efebff',
        'surface-container-low': '#f6f2ff',
        'surface-container-high': '#e9e5ff',
        'surface-container-highest': '#e3dfff',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e3dfff',
        'surface-tint': '#494bd6',
        'on-surface': '#181445',
        'on-surface-variant': '#464554',
        'inverse-surface': '#2d2a5b',
        'inverse-on-surface': '#f3eeff',
        'background': '#fcf8ff',
        'on-background': '#181445',
        'outline': '#767586',
        'outline-variant': '#c7c4d7',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        'headline': ['Hanken Grotesk', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      spacing: {
        'gutter': '24px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
        'unit': '8px',
      },
      maxWidth: {
        'content': '1280px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'card': '0 4px 12px rgba(30, 27, 75, 0.05)',
        'card-hover': '0 8px 24px rgba(30, 27, 75, 0.08)',
        'nav': '0 -4px 12px rgba(30, 27, 75, 0.05)',
        'primary-lg': '0 8px 32px rgba(70, 72, 212, 0.2)',
        'glow': '0 4px 20px -2px rgba(30, 27, 75, 0.08)',
      },
    },
  },
  plugins: [],
};
