/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#dfe3e8',
        'on-error': '#ffffff',
        'secondary': '#4a6363',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#b9caff',
        'outline': '#6f7979',
        'on-tertiary-fixed': '#001848',
        'on-background': '#181c20',
        'on-primary-fixed-variant': '#004f54',
        'secondary-fixed': '#cce8e7',
        'on-secondary-fixed-variant': '#324b4b',
        'tertiary-fixed': '#dae2ff',
        'primary-fixed': '#a1eff7',
        'surface': '#f7f9ff',
        'surface-container-high': '#e5e8ee',
        'background': '#f7f9ff',
        'inverse-primary': '#85d3db',
        'tertiary': '#133a87',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#b1cccb',
        'on-surface': '#181c20',
        'secondary-container': '#cce8e7',
        'inverse-surface': '#2d3135',
        'primary': '#00464b',
        'surface-tint': '#006970',
        'primary-fixed-dim': '#85d3db',
        'tertiary-fixed-dim': '#b2c5ff',
        'on-secondary-container': '#506969',
        'inverse-on-surface': '#eef1f7',
        'on-secondary': '#ffffff',
        'on-primary-container': '#8ad8e0',
        'on-secondary-fixed': '#051f20',
        'error-container': '#ffdad6',
        'surface-bright': '#f7f9ff',
        'surface-container': '#ebeef4',
        'on-primary-fixed': '#002022',
        'primary-container': '#006066',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'on-surface-variant': '#3f4949',
        'outline-variant': '#bec8c9',
        'surface-container-highest': '#dfe3e8',
        'surface-container-low': '#f1f4fa',
        'on-tertiary-fixed-variant': '#1f428f',
        'surface-dim': '#d7dae0',
        'tertiary-container': '#3152a0',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'card': '0 12px 32px -4px rgba(0,70,75,0.08)',
        'card-hover': '0 16px 40px -4px rgba(0,70,75,0.12)',
        'nav': '0 -4px 20px rgba(0,70,75,0.05)',
        'primary-lg': '0 8px 32px rgba(0,70,75,0.2)',
      },
    },
  },
  plugins: [],
};
